# Generated by Django 4.0.2 on 2022-02-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='uploadedPapers')),
            ],
        ),
        migrations.DeleteModel(
            name='PaperExample',
        ),
    ]
